### PR TITLE
mod_trust_clientip: check remote addr private when stats

### PR DESCRIPTION
**Pull request by kwanhur**
it supports `IPv4` `IPv6` and solves #856

### CODE REVIEW

**Comment by kwanhur** [comment]
it built failed, because ci env vm go version was under 1.17.

should add step `specify go-version` on build job.

**Review by iyangsj — APPROVED** [review]

**Comment by kwanhur** [comment]
CI checks failed, because go version under 1.17 when create pull request.

Need to check it again :-)

**Comment by kwanhur** [comment]
> it built failed, because ci env vm go version was under 1.17.
> 
> should add step `specify go-version` on build job.

has been under by #964

**Comment by kwanhur** [comment]
> Try to pull latest change from upstream and update you code base, then push a new commit for your code change? which would trigger this ci to use the new workflow in change #964 I think.

thank you :-)

**Comment by kwanhur** [comment]
> CI checks failed, because go version under 1.17 when create pull request.
> 
> Need to check it again :-)

All the checks have passed

**Comment by daimg** [comment]
Thanks for the work. Could you please also update docs/en_us/installation/install_from_source.md and docs/zh_cn/installation/install_from_source.md to reflect required golang version after your enhancement?

**Comment by kwanhur** [comment]
> Thanks for the work. Could you please also update docs/en_us/installation/install_from_source.md and docs/zh_cn/installation/install_from_source.md to reflect required golang version after your enhancement?

#976 submits to do it, doesn't merge with this PR.

**Pull request merged**
